version: '3.10'
services:
  web:
    build:
      context: ./innotter
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./innotter/:/usr/src/app/innotter
    ports:
      - "8000:8000"
    env_file:
      - ./innotter/.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=DATABASE_USER
      - POSTGRES_PASSWORD=DATABASE_PASS
      - POSTGRES_DB=DATABASE_NAME

volumes:
  postgres_data: