pipeline {
    agent {
        docker {
                image 'python:3.8'
                args "--user root --privileged"
        }
    }

    stages {
        stage('Build') {

            stages {
                stage('Install dependencies') {
                    steps {
                        sh 'pip install -U pipenv'
                        sh 'pipenv install --system'
                    }
                }
                stage('Autoformat') {
                    steps {
                        sh 'isort .'
                        sh 'black .'

                    }
                }
                stage('Lint') {
                    steps {
                        sh 'flake8'
                    }
                }
            }
        }
    }
}

