# Generated by Django 4.1.4 on 2022-12-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_page_follow_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
