# Generated by Django 4.1.4 on 2023-01-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_likes_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
    ]
