# Generated by Django 4.1.5 on 2023-01-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_likes_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
