# Generated by Django 4.1.5 on 2023-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_like_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
