# Generated by Django 4.1.5 on 2023-01-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_like_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date',
        ),
    ]
