# Generated by Django 4.1.7 on 2023-02-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_page_id_alter_page_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='uuid',
            new_name='id',
        ),
    ]
