# Generated by Django 4.1.7 on 2023-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')],
                                   default='user', max_length=9),
        ),
    ]
