version: '3.8'
services:
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "8080:8080"
    depends_on:
      - ddb
    networks:
      - microservices

  ddb:
    image: amazon/dynamodb-local
    restart: unless-stopped
    ports:
      - 8000:8000
    user: root
    volumes:
      - ./dynamo_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 8000"
    networks:
      - microservices

  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    ports:
    - 8001:8001
    volumes:
      - ./dynamodb:/data
    env_file:
      - ./.env
    depends_on:
      - ddb
    networks:
      - microservices

networks:
  microservices:
    name: microservices

volumes:
  dynamo_data: